function value_conv = conv_unit(unit_in, unit_out, value)
% Converts a unit into another using a unified conversion dictionary with category checks
% Works in MATLAB 2025b (no illegal struct field names)

    % Map user-friendly names to valid struct field names
    nameMap = containers.Map( ...
        {'m/s','m/s^2','ft/s^2','n/m^2','n/mm^2'}, ...
        {'mps','mps2','ftps2','pa','nmm2'} ...
    );

    % Replace invalid unit names if necessary
    if isKey(nameMap, lower(unit_in))
        unit_in = nameMap(lower(unit_in));
    end
    if isKey(nameMap, lower(unit_out))
        unit_out = nameMap(lower(unit_out));
    end

    % Unified conversion factors in SI units (valid field names only)
    units = struct(...
        ... % Length
        'in',      struct('factor', 0.0254, 'category', 'length'), ...
        'inch',    struct('factor', 0.0254, 'category', 'length'), ...
        'm',       struct('factor', 1,      'category', 'length'), ...
        'mm',      struct('factor', 1e-3,   'category', 'length'), ...
        'km',      struct('factor', 1e3,    'category', 'length'), ...
        'nm',      struct('factor', 1852,   'category', 'length'), ...
        'ft',      struct('factor', 0.3048, 'category', 'length'), ...
        ... % Force
        'n',       struct('factor', 1,      'category', 'force'), ...
        'kn',      struct('factor', 1e3,    'category', 'force'), ...
        'ibf',     struct('factor', 4.44822,'category', 'force'), ...
        'kibf',    struct('factor', 4448.22,'category', 'force'), ...
        ... % Weight (mass)
        'kg',      struct('factor', 1,       'category', 'weight'), ...
        'g',       struct('factor', 1e-3,    'category', 'weight'), ...
        't',       struct('factor', 1e3,     'category', 'weight'), ...
        'lbs',     struct('factor', 0.453592,'category', 'weight'), ...
        ... % Velocity
        'kts',     struct('factor', 0.514444, 'category', 'velocity'), ...
        'kt',      struct('factor', 0.514444, 'category', 'velocity'), ...
        'mps',     struct('factor', 1,        'category', 'velocity'), ...
        'kmh',     struct('factor', 0.277778, 'category', 'velocity'), ...
        'kph',     struct('factor', 0.277778, 'category', 'velocity'), ...
        'fpm',     struct('factor', 0.00508,  'category', 'velocity'), ...
        ... % Acceleration
        'mps2',    struct('factor', 1,        'category', 'acceleration'), ...
        'ftps2',   struct('factor', 0.3048,   'category', 'acceleration'), ...
        ... % Volume
        'l',       struct('factor', 1e-3,     'category', 'volume'), ...
        'm3',      struct('factor', 1,        'category', 'volume'), ...
        'gal_uk',  struct('factor', 4.54609e-3,'category','volume'), ...
        'gal_us',  struct('factor', 3.78541e-3,'category','volume'), ...
        ... % Area
        'mm2',     struct('factor', 1e-6,     'category','area'), ...
        'ft2',     struct('factor', 0.092903, 'category','area'), ...
        'm2',      struct('factor', 1,        'category','area'), ...
        ... % Angle
        'rad',     struct('factor', 1,        'category','angle'), ...
        'degree',  struct('factor', pi/180,   'category','angle'), ...
        ... % Pressure
        ... % Base: SI = 1 Pa = 1 N/m^2
        'pa',      struct('factor', 1,        'category','pressure'), ...      % Pascal
        'nm2',      struct('factor', 1,        'category','pressure'), ...      % N/m^2 = Pascal
        'nmm2',    struct('factor', 1e6,      'category','pressure'), ...      % N/mm^2 (1 mm² = 1e-6 m²)
        'kpa',     struct('factor', 1e3,      'category','pressure'), ...
        'mpa',     struct('factor', 1e6,      'category','pressure'), ...
        'bar',     struct('factor', 1e5,      'category','pressure') ...       % 1 bar = 100,000 Pa
    );

    % Normalize input
    unit_in = lower(unit_in);
    unit_out = lower(unit_out);

    % Validate units
    if ~isfield(units, unit_in)
        error('Invalid input unit: "%s".', unit_in);
    end
    if ~isfield(units, unit_out)
        error('Invalid output unit: "%s".', unit_out);
    end

    % Check category compatibility
    if ~strcmp(units.(unit_in).category, units.(unit_out).category)
        error('Conversion from "%s" to "%s" is not allowed (category mismatch).', ...
            unit_in, unit_out);
    end

    % Convert
    factor_in  = units.(unit_in).factor;
    factor_out = units.(unit_out).factor;

    value_SI = value * factor_in;
    value_conv = value_SI / factor_out;
end
